---
name: eliud_pkg_follow_model
description: eliud_pkg_follow_model is the model package for the package eliud_pkg_follow. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_follow_model
version: 1.0.0
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  eliud_core_main:                                                                                   # ANDROID IOS             WEB
    path: ../eliud_core_main
  eliud_core_helpers:                                                                                # ANDROID IOS             WEB
    path: ../eliud_core_helpers
  eliud_pkg_etc_model:                                                                               # ANDROID IOS             WEB
    path:  ../eliud_pkg_etc_model

  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  flutter_bloc: ^8.1.3
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
